---
- name: Converge
  hosts: all
  vars:
    expected_cmdline: >-
      old params
      some extra stuff=true
      transparent_hugepage=never default_hugepagesz=2M hugepagesz=2M hugepages=184320
    kernel_cmdline:
      - transparent_hugepage=never
      - default_hugepagesz=2M
      - hugepagesz=2M
      - hugepages=184320
    kernel_cmdline_remove:
      - hugepage
  tasks:
    - include_role:
        name: stackhpc.grubcmdline
  handlers:
    # Simulate /proc/cmdline getting updated via reboot
    - name: create dummy cmdline
      copy:
        content: "{{ expected_cmdline }}"
        dest: /tmp/dummy-cmdline
      listen: reboot
    - name: bind mount dummy cmdline
      mount:
        src: /tmp/dummy-cmdline
        path: /proc/cmdline
        opts: bind
        state: mounted
        fstype: none
      listen: reboot
